services:
  - docker

git:
  depth: 2

branches:
  only:
  - master

language: node_js
node_js: "12"

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages: libxkbfile-dev
    chrome: stable

env:
  - NPM_TAG=latest IMAGE_NAME=theia-full
  - NPM_TAG=next IMAGE_NAME=theia-full
  - NPM_TAG=latest IMAGE_NAME=theia
  - NPM_TAG=next IMAGE_NAME=theia
  - NPM_TAG=latest IMAGE_NAME=theia-java
  - NPM_TAG=next IMAGE_NAME=theia-java
  - NPM_TAG=latest IMAGE_NAME=theia-go
  - NPM_TAG=next IMAGE_NAME=theia-go
  - NPM_TAG=latest IMAGE_NAME=theia-python
  - NPM_TAG=next IMAGE_NAME=theia-python
  - NPM_TAG=latest IMAGE_NAME=theia-swift
  - NPM_TAG=next IMAGE_NAME=theia-swift
  - NPM_TAG=latest IMAGE_NAME=theia-cpp
  - NPM_TAG=next IMAGE_NAME=theia-cpp
  - NPM_TAG=next IMAGE_NAME=theia-rust
  - NPM_TAG=latest IMAGE_NAME=theia-dart
  - NPM_TAG=next IMAGE_NAME=theia-dart
  - NPM_TAG=latest IMAGE_NAME=theia-https ENV_VARS="-e token=" PORT=10443
  - NPM_TAG=next IMAGE_NAME=theia-https ENV_VARS="-e token=" PORT=10443
  - NPM_TAG=latest IMAGE_NAME=theia-php
  - NPM_TAG=next IMAGE_NAME=theia-php

jobs:
  # add installer builds to jobs matrix
  include:
    - &publish
      env:
      install: skip
      script: cd theia-electron && yarn && travis_wait 30 yarn package
    - <<: *publish
      os: osx
    - <<: *publish
      os: windows

before_install:
- npm install -g yarn eclint
- eclint check "**/*" || echo "Warning! Formatting errors encountered..."

install:
  # this makes it possible to see output of the docker build as it unfolds:
  # from https://stackoverflow.com/questions/43918874/how-to-increase-no-activity-wait-time-in-travis-ci
  - "travis_wait 30 sleep 1800 &"
  # check if there were changes since the previous commit in this image
  # if not (script returns 137) then the build process is terminated
  - ./check_changed.sh $IMAGE_NAME ; RETURN_CODE=$? ; if [ $RETURN_CODE -eq 137 ]; then travis_terminate 0; elif [ $RETURN_CODE -ne 0 ]; then travis_terminate $RETURN_CODE; fi
  - ./build_container.sh $NPM_TAG $IMAGE_NAME $NODE_VERSION $PORT $ENV_VARS

script: cd tests; yarn; yarn test-app-$IMAGE_NAME

after_failure:
  script: cd $TRAVIS_BUILD_DIR && ./commit_screenshots.sh

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push "theiaide/$IMAGE_NAME"
  on:
    branch: master
    condition: $IMAGE_NAME
  skip_cleanup: true

notifications:
  on_success: change
  on_failure: always
  on_start: never
